using System.ComponentModel.DataAnnotations;

namespace Domain.Primitives;

public abstract class Entity
{
    private readonly IList<IDomainEvent> _domainEvents = new List<IDomainEvent>();

    public IReadOnlyCollection<IDomainEvent> DomainEvents => [.. _domainEvents];
    [Key]
    public int Id { get; set; }

    [Required]
    public DateTimeOffset CreatedAt { get; set; } = DateTime.UtcNow;

    [Required]
    public string CreatedBy { get; set; } = string.Empty;

    public DateTimeOffset? UpdatedAt { get; set; }

    [Required]
    public bool IsDeleted { get; set; } = false;

    /// <summary>
    /// Since I'm using  Auto Incremented ID, I need to have a unique identifier generated by client for the Outbox pattern to correctly persist and ID before saving.
    /// </summary>
    public Guid ClientGeneratedId { get; init; } = Guid.NewGuid();



    protected void RaiseDomainEvent(IDomainEvent domainEvent)
    {
        if (domainEvent is null) throw new ArgumentNullException(nameof(domainEvent), "Domain event cannot be null");
        _domainEvents.Add(domainEvent);
    }

    public void ClearDomainEvents() { _domainEvents.Clear(); }

}
